### ISSUE TITLE
Move: 파일 순서 정리 및 변경

### ISSUE THREAD

**Issue by yangsubinn** [SOPT-29th-Joint-Seminar-3/client-iOS#34]
### To do🎧
<img width="282" alt="스크린샷 2021-12-03 오후 10 14 53" src="https://user-images.githubusercontent.com/81167570/144608537-688623d0-da69-486c-9b4c-601c9532eefc.png">

컨벤션 정했던 것을 바탕으로 파일 순서를 좀 통일감있게 정리해볼까 하는데.. 해보고 아니면 그냥 마지막 이슈로 아련하게 남겨두겠습니다
혹시 Views 안에 있는 파일들 xib랑 Cell로 분류해서 폴더링 해도 될까여?

@Taehyeon-Kim @dev-madilyn

**Comment by dev-jungbin** [comment]
🥕 빠따여

**Comment by Taehyeon-Kim** [comment]
너무 좋아요~~!~!~!
